[colors.primary]
background = "#1e1d27"
foreground = "#e7e3ff"

[colors.normal]
black = "#2a2931"
red = "#f9f5af"
green = "#ff2980"
yellow = "#7657ff"
blue = "#5600ff"
magenta = "#971448"
cyan = "#705fba"
white = "#d2cdff"

[colors.bright]
black = "#5f5584"
red = "#f9f5af"
green = "#ff2980"
yellow = "#7657ff"
blue = "#5600ff"
magenta = "#971448"
cyan = "#705fba"
white = "#d2cdff"

[cursor.style]
shape = "Underline"

[window]
opacity=0.6
